### ISSUE TITLE
Simplify config.yaml - connstrings everywhere!

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/black-box#9]
We could just base the entire system on connstrings. For example, here's how our config might look:

```yaml
databases:
- mongodb://username:password@host:port
- postgres://username:password@host:port

logging:
- ssh://username:password@host:port

storage:
- gdrive://username:token

rotation_days: 7
```

And based on this, it'll figure out what's enabled, what's disabled, and how to log into all these services. There's no need for enabled bools and environment variables and whatever. We'll just pass custom connstrings for every service and every type, and repurpose our connstring parser to work for any connstring.

When writing a generic connstring parser, we should try to adhere to the connstring specs used by Postgres and Mongo - for example, every part of the connstring is optional, so `postgres://` is a valid connstring, as is `postgresql://user@host`. We should also support optional params in the parser.
- [MongoDB connstrings](https://docs.mongodb.com/manual/reference/connection-string/)
- [LibPQ connstrings](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)
